# Generated by Django 3.2.7 on 2021-10-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_reviews', models.TextField(blank=True, max_length=200)),
                ('name', models.TextField(blank=True, max_length=200)),
                ('popular_tags', models.TextField(blank=True, max_length=200)),
                ('URL', models.TextField(max_length=200)),
            ],
        ),
    ]
