# Generated by Django 3.2.7 on 2021-10-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20211003_0014'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='steam_gameinfo',
            table=None,
        ),
    ]
